### PR TITLE
As long as chrony or ntp is selected as well, we may not need to

### PR DESCRIPTION
**Pull request by BryanQuigley**
hardcode ntp depends in systemd itself.

Even if it timesync does get installed it won't harm anything and
will just allow ntp to be the default.

Either way, moving from ntp makes sense.

More here: https://community.endlessos.com/t/xterm-shows-in-3-10/16322/18

### CODE REVIEW

**Comment by jprvita** [comment]
Hey Brian, thanks for your contribution and for raising the dicussion around dropping ntp / fake-hwclock in favor of systemd-timesyncd. After some internal discussion, in addition to the forum discussion you pointed in the description, we agreed that it makes sense to move over to systemd-timesyncd.

Before I merge this, could you please turn your commit into a revert commit (i.e., created with `git revert` with the subject `Revert "<original subject>"`) instead of using a different commit subject, so it is easier to spot on the next upgrade (our upgrades workflow is a bit unorthodox, as you may have noticed from the repo history). Please keep the link to the forum discussion on the commit message.

In addition, before we drop the ntp package we also need to revert https://github.com/endlessm/systemd/commit/18be2ab3dde77ec57474d3792c2038221e855b6a on the main code branch -- would you open an additional PR for that (or I could take care of that part)?

**Comment by BryanQuigley** [comment]
This PR's part is done.

My master branch doesn't seem to like cleanly pulling from the current master branch.  I'd nuke it and start over.. but not this with this PR open :).

**Comment by jprvita** [comment]
ok to test

**Comment by jprvita** [comment]
> This PR's part is done.
> 

Great, thanks! I'll merge this once CI is green.

> My master branch doesn't seem to like cleanly pulling from the current master branch. I'd nuke it and start over.. but not this with this PR open :).

That is because when we update to a new upstream version we rebase our downstream changes on top of upstream and force-push over our master branch (since normally we are not really upstream to anyone else). You can fix that by resetting your local master branch to the remote master ref. So, something like this (assuming the remote pointing to this repo is named `origin`):

```
git checkout master
git fetch --prune origin
git reset --hard origin/master
```
The `--prune` above is to cleanup any stale pointers to references on this remote that you may have locally that do not exist on the remote anymore.

**Review by jprvita — APPROVED** [review]

**Pull request merged**
