### PR TITLE
Don't automount the ESP on /boot

### PR DESCRIPTION
**Pull request by dbnicholson**
This is a workaround for ostree staged deployments as mentioned in the commit message. I'm posting this so it's out there, but I haven't tested it, nor has it been agreed this is the way to go. The first commit is likely fallout from the recent meson update. It can be split out if necessary.

https://phabricator.endlessm.com/T33136

### CODE REVIEW

**Comment by wjt** [comment]
Looks like there is another failure to build… maybe worth splitting that & the meson patches?

**Comment by dbnicholson** [comment]
> Looks like there is another failure to build… maybe worth splitting that & the meson patches?

Right. I thought I got closer doing this locally, but let me get that working first.

**Comment by dbnicholson** [comment]
I split the build fixes out into #144 and rebased this PR on top of it.

**Comment by wjt** [comment]
We fixed this with https://github.com/ostreedev/ostree/pull/2544 which essentially makes the mount persistent as soon as an update is staged.

**Pull request closed without merging**
